site_name: SRIP004-KDL Work Documentation

nav:
  - Welcome: 'index.md'
  - Tech Stack: 'tech-stack.md'
  - Setup - Development Environment: 'setup-devenv.md'
  - Setup - Server: 'setup-server.md'
  - Workflow: 'workflow.md'
  - Source Code:
      - index.php: "source-code/index.php.md"
      - form-upload.php: "source-code/form-upload.php.md"
      - data-catalog.php: "source-code/data-catalog.php.md"
      - druid-status.php: "source-code/druid-status.php.md"
      - retrieval.php: "source-code/retrieval.php.md"
      - metadata-viewer.php: "source-code/metadata-viewer.php.md"
      - fetch.php: "source-code/fetch.php.md"
      - druid-query.php: "source-code/druid-query.php.md"
      - upload.php: "source-code/upload.php.md"
      - upload-batch.php: "source-code/upload-batch.php.md"
      - helper.php: "source-code/helper.php.md"
      - csv-from-druid.php: "source-code/csv-from-druid.php.md"
      - druid_lib.py: "source-code/druid_lib.py.md"
      - fetch_catalog.py: "source-code/fetch_catalog.py.md"
      - fetch_rows.py: "source-code/fetch_rows.py.md"
      - get_tasks.py: "source-code/get_tasks.py.md"
      - logger.py: "source-code/logger.py.md"
      - metadata_writer.py: "source-code/metadata_writer.py.md"
      - pydruid_hepler.py: "source-code/pydruid_helper.py.md"
      - query_exec.py: "source-code/query_exec.py.md"
      - settings.py: "source-code/settings.py.md"
      - upload_batch_druid.py: "source-code/upload_batch_druid.py.md"
      - upload_single_druid.py: "source-code/upload_single_druid.py.md"
      - csv-from-druid.py: "source-code/csv_from_druid.py.md"
      - xlsx2csv.py: "source-code/xlsx2csv.py.md"
      - js/druid-query.js: "source-code/js_druid-query.js.md"
      - js/generate-checkboxes.js: "source-code/js_generate-checkboxes.js.md"
      - js/upload-batch.js: "source-code/js_upload-batch.js.md"
      - js/retrieval.js: "source-code/js_retrieval.js.md"
      - js/query-table-builder.js: "source-code/js_query-table-builder.js.md"
      - js/metadata-tree.js: "source-code/js_metadata-tree.js.md"
      - js/ace-1.5.0: "source-code/js_ace1.5.0.md"
      - styles/tables.css: "source-code/styles_tables.css.md"

theme: 
  palette:
    primary: red
  features:
    - navigation.sections
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences